"""Generate recalibrated rubric_prompts.json"""
import json

DECISION_RULES_TEMPLATE = """DECISION RULES:
1. EVIDENCE REQUIREMENT: A rating of aligned or exceptional REQUIRES at least one verbatim evidence_quote from the supplied content. No quote = cannot be aligned.
2. ABSENCE RULE: If the supplied content does not contain the required evidence for alignment, the rating CANNOT be aligned — absence of evidence is not alignment.
3. UNREADABLE CONTENT: If content is binary data, garbled text, or otherwise unreadable, treat it as absent.
4. Choose approaching when the element is partially addressed but missing required components.
5. Choose incomplete when the required feature is not found at all.
6. Do NOT infer alignment from course structure alone — explicit evidence must be present in the text.
7. Truncation: If a truncation note is present, judge available evidence normally."""

RESPONSE_DISCIPLINE = """RESPONSE DISCIPLINE:
- Use no more than 2 short, decisive evidence quotes. Incomplete and not_evaluable may use zero quotes.
- Return no more than 3 brief missing_items. Keep suggested_fix and reasoning to 2 short sentences max."""

OUTPUT_TEMPLATE = 'OUTPUT: Return JSON: {{"element_id": "{eid}", "rating": "<rating>", "confidence": <0.0-1.0>, "evidence_quotes": [{{"quote": "<verbatim>", "page_id": "<id>", "page_title": "<title>"}}], "missing_items": ["<what is absent>"], "suggested_fix": "<concrete action>", "reasoning": "<brief explanation>"}}.'

elements = {}

# Element 1.1
elements["1.1"] = {
    "id": "1.1",
    "title": "Course Policies",
    "section": "1",
    "context_scope": ["syllabus", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 1.1 — Course Policies",
        "",
        "WHAT THIS EVALUATES: Whether the course clearly states policies that support student success (academic honesty, withdrawal, work submission, communication, participation) and makes them accessible to students.",
        "",
        "WHERE TO LOOK: Syllabus, Orientation/Getting Started module, and any dedicated policy pages.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Explicit academic honesty/integrity policy with clear expectations",
        "- Withdrawal or drop policy explaining process",
        "- Work submission policy (deadlines, late work, format)",
        "- Communication policy (contact methods, response times)",
        "- Participation policy (engagement expectations)",
        "- At least three of the five areas substantively addressed",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Fewer than three of the five policy areas are substantively addressed",
        "- Policies exist only as vague references without actionable expectations",
        "- Policy content is a binary/corrupt file that cannot be read as text",
        "- Only generic institutional boilerplate with no course-specific expectations",
        "",
        "RATING SCALE:",
        "- incomplete: No course policies found, or content is unreadable (binary file, corrupt data).",
        "- approaching: Fewer than three of the five policy areas are substantively addressed, OR policies are present but fundamentally unclear.",
        "- aligned: At least three of the five policy areas (academic honesty, withdrawal, work submission, communication, participation) are clearly stated with specific expectations. Policies appear in at least one accessible location. Placeholder text for campus-specific details does not disqualify alignment if policy intent is clear.",
        "- exceptional: Meets ALL aligned criteria AND relevant policies are also included within units or activities where they are most useful.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="1.1"),
    ])
}

# Element 1.2
elements["1.2"] = {
    "id": "1.2",
    "title": "Equitable Use of Technology",
    "section": "1",
    "context_scope": ["syllabus", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 1.2 — Equitable Use of Technology",
        "",
        "WHAT THIS EVALUATES: Whether the instructor explains how required technology supports learning, provides guidance for accessing tools, and offers information about obtaining tech support.",
        "",
        "WHERE TO LOOK: Syllabus, Orientation/Getting Started module, and assignment instructions where technology is used.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A list or explanation of required technology tools with their purpose",
        "- Instructions for accessing the technology (links, downloads, login info)",
        "- Information about where to obtain technical support (help desk, phone, link)",
        "- Browser requirements or device recommendations",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Technology tools used in the course are never identified or explained",
        "- No access guidance provided (no links, no download instructions, no login info)",
        "- Technical support information completely absent",
        "- Tools mentioned only by name with zero context about purpose or access",
        "",
        "RATING SCALE:",
        "- incomplete: No explanation of required technology found in the course content.",
        "- approaching: Technology is mentioned but students are given no guidance on how to access it AND no tech support information is provided.",
        "- aligned: The instructor identifies required technology, explains how it supports learning, and provides guidance for accessing tools and obtaining tech support. Using institutionally provided tools (Canvas, Zoom, LMS-integrated tools) implicitly meets accessibility requirements — an explicit accessibility statement is NOT required.",
        "- exceptional: Meets ALL aligned criteria AND offers flexibility or alternative options to support equitable access.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="1.2"),
    ])
}

# Element 1.3
elements["1.3"] = {
    "id": "1.3",
    "title": "Artificial Intelligence (AI)",
    "section": "1",
    "context_scope": ["syllabus", "pages", "assignments"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 1.3 — Artificial Intelligence (AI)",
        "",
        "WHAT THIS EVALUATES: Whether the course includes a student-centered, course-specific AI approach that clearly communicates expectations for how AI may or may not be used, and whether the instructor addresses their own AI use in the course.",
        "",
        "WHERE TO LOOK: Syllabus, course policies page, Orientation/Start Here module, dedicated AI pages, and assignment instructions.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Course-specific AI content that addresses how AI relates to the course (not just a generic academic honesty statement)",
        "- Clear communication of whether/when/how AI tools may be used by students — this can take the form of a formal policy statement OR instructional content that teaches students about AI use with explicit guidance on appropriate use in the course context",
        "- Instructor addresses their own relationship to AI in the course (disclosure of use, teaching about AI, or incorporating AI activities)",
        "- AI guidance placed in an accessible, findable location",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No AI-related content, policy, or guidance found anywhere in the course",
        "- Only a generic academic honesty statement that does not specifically address AI tools",
        "- AI mentioned only in passing (e.g., a single sentence) without substantive guidance on student use",
        "- No indication of whether/how the instructor engages with AI in the course",
        "",
        "CRITICAL CLARIFICATION FOR EVALUATORS:",
        "- A page or module that teaches students about AI AND provides concrete strategies for using AI in their coursework (e.g., 'use AI to summarize articles', 'use AI to generate topic ideas', 'use AI as an editor') IS a course-specific AI approach — it communicates expectations by showing students how to use AI for this course's assignments.",
        "- An instructor who creates AI lessons, discusses their relationship with AI tools, or says things like 'I'm not telling you not to use it' IS addressing their stance on AI use.",
        "- The aligned rating does NOT require a formal document labeled 'AI Policy' — substantive AI content with usage guidance qualifies.",
        "",
        "RATING SCALE:",
        "- incomplete: No AI policy, guidance, or substantive AI content found in the course.",
        "- approaching: Some mention of AI exists but guidance is generic, unclear, or missing key components (no clear student use expectations OR no instructor AI disclosure).",
        "- aligned: The course includes a student-centered, course-specific approach to AI that is clearly communicated and easy to find. This may be a formal policy statement OR substantive instructional content about AI that includes clear guidance on how students should/may use AI tools in their coursework. The instructor's own AI use or stance is addressed. IMPORTANT: A dedicated AI education module that (a) discusses ethical considerations of AI, (b) provides strategies for students to use AI tools (e.g., summarizing, brainstorming, editing, generating ideas), and (c) shows the instructor actively incorporating AI into teaching qualifies as a course-specific AI approach — even without a formal 'policy' header. The presence of guidance like 'here is how to use AI for this course' is functionally equivalent to a policy.",
        "- exceptional: Meets ALL aligned criteria AND AI guidance is integrated into specific course activities and assignments with point-of-use instructions.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="1.3"),
    ])
}

# Element 1.4
elements["1.4"] = {
    "id": "1.4",
    "title": "Data Privacy and Security",
    "section": "1",
    "context_scope": ["syllabus", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 1.4 — Data Privacy and Security",
        "",
        "WHAT THIS EVALUATES: Whether the course provides students with guidance on safe technology use and references institutional privacy/security policies or practices.",
        "",
        "WHERE TO LOOK: Syllabus, Orientation/Getting Started module, tech support pages, and instructions for activities using external tools.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Link or reference to institution's privacy and/or security policies",
        "- Guidance for safe technology use (protect credentials, use secure connections, set videos to private/unlisted)",
        "- Privacy considerations mentioned when external tools require account creation",
        "- References to institutional data handling (FERPA, LMS security)",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No privacy or security information of any kind in the course",
        "- External tools required with no mention of privacy",
        "- No guidance about safe practices online anywhere in the content",
        "- Privacy topic never explicitly addressed — cannot be inferred from tool usage alone",
        "",
        "RATING SCALE:",
        "- incomplete: No privacy/security information or guidance found in the course content.",
        "- approaching: Only a passing mention of privacy with no actionable student guidance and no link to institutional policies.",
        "- aligned: The course provides students with guidance on safe technology use AND references or links to institutional privacy/security policies. Guidance such as setting videos to private/unlisted, protecting credentials, or following institutional security practices counts. If the course uses ONLY institutionally managed tools, a reference to institutional privacy handling satisfies this.",
        "- exceptional: Meets ALL aligned criteria AND provides opportunities for students to understand digital privacy best practices.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="1.4"),
    ])
}

# Element 1.5
elements["1.5"] = {
    "id": "1.5",
    "title": "Student Resources and Support",
    "section": "1",
    "context_scope": ["syllabus", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 1.5 — Student Resources and Support",
        "",
        "WHAT THIS EVALUATES: Whether the course provides clearly labeled, easy-to-find links to institutional support services including disability services, counseling, tutoring, library, basic needs, and technology help.",
        "",
        "WHERE TO LOOK: Syllabus, Orientation/Getting Started module, or a dedicated Student Resources page.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Links to disability/accessibility services",
        "- Links to tutoring services",
        "- Links to counseling or student support services",
        "- Links to library resources",
        "- Links to technology help or help desk",
        "- Links to basic needs support (food, housing, emergency assistance)",
        "- At least four of these six service categories addressed with actual links or clear references",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Fewer than four of the six service categories have links or references",
        "- Services mentioned by name but no links or contact info provided",
        "- Resources buried and difficult to locate",
        "- Only tutoring or only tech support provided without broader support services",
        "",
        "RATING SCALE:",
        "- incomplete: No links to institutional support services found.",
        "- approaching: Some support links present but fewer than four of the six categories covered, or links are difficult to locate.",
        "- aligned: Links to institutional support services covering at least four of these six categories — disability services, counseling, tutoring, library, basic needs, and technology help — are clearly labeled and easy to find.",
        "- exceptional: Meets ALL aligned criteria AND support resources are integrated into relevant course activities with reminders throughout.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="1.5"),
    ])
}

# Element 1.6
elements["1.6"] = {
    "id": "1.6",
    "title": "Learning Support",
    "section": "1",
    "context_scope": ["pages", "assignments"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 1.6 — Learning Support",
        "",
        "WHAT THIS EVALUATES: Whether the course includes support resources within modules and activities to help students successfully complete assignments (tips, reminders, tutorials, helpful links).",
        "",
        "WHERE TO LOOK: Module pages, assignment instructions, discussions, and announcements tied to course activities.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Tips or reminders placed within assignments or modules",
        "- Links to tutorials or guides that clarify challenging concepts",
        "- Writing center, tutoring, or study skill resources linked near relevant activities",
        "- Learning support materials integrated into module content (not only in the syllabus or orientation)",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No learning support resources included within course activities",
        "- Resources appear only in orientation/syllabus and never within modules",
        "- Support materials are rare or isolated (only in one module)",
        "- Content pages list assignments without tips, guidance, or supportive resources",
        "",
        "RATING SCALE:",
        "- incomplete: No learning support resources (tips, reminders, helpful links) found within course activities.",
        "- approaching: Some support resources present but isolated to one area or only in the syllabus/orientation; not integrated into modules where students do work.",
        "- aligned: The course includes support resources within modules and activities to assist students, such as tips, reminders, helpful resource links, or tutorials. These appear in more than one module, demonstrating integration throughout the course.",
        "- exceptional: Meets ALL aligned criteria AND provides additional resources for deeper exploration, placed within activities where they best support learning.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="1.6"),
    ])
}

# Element 2.1
elements["2.1"] = {
    "id": "2.1",
    "title": "Structure and Navigation",
    "section": "2",
    "context_scope": ["modules", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 2.1 — Structure and Navigation",
        "",
        "WHAT THIS EVALUATES: Whether Canvas tools and modules are used consistently to organize content, provide a clear structure that is easy to navigate, and employ accessible navigation and formatting practices.",
        "",
        "WHERE TO LOOK: Home page, Modules area, course navigation menu, and Start Here/Orientation module.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A clearly labeled starting point (Start Here, Orientation, or Welcome module)",
        "- Consistent module organization and naming conventions",
        "- Instructions or guidance explaining how to navigate the course",
        "- Consistent format across modules (e.g., overview, materials, activities pattern)",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No clear starting point for students",
        "- Modules inconsistently organized or use confusing naming",
        "- No navigation guidance anywhere in the course",
        "- Module structure varies wildly from unit to unit",
        "",
        "RATING SCALE:",
        "- incomplete: No consistent structure or navigation guidance found; course lacks a clear starting point.",
        "- approaching: Some structure present but inconsistent module organization, unclear naming, or missing navigation guidance.",
        "- aligned: Modules are used consistently to organize content with a clear starting point, logical naming conventions, and a navigable structure. Navigation guidance or a clear orientation helps students understand how to move through the course.",
        "- exceptional: Meets ALL aligned criteria AND the course is designed for inclusive access across multiple devices with technology recommendations throughout.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="2.1"),
    ])
}

# Element 2.2
elements["2.2"] = {
    "id": "2.2",
    "title": "Module Objectives",
    "section": "2",
    "context_scope": ["modules", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 2.2 — Module Objectives",
        "",
        "WHAT THIS EVALUATES: Whether module learning objectives are consistently placed and describe specific, measurable outcomes that align to course-level objectives.",
        "",
        "WHERE TO LOOK: Beginning of each module, module overview pages, or module introductions.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Objectives present in the majority of modules (not just one or two)",
        "- Objectives written using measurable action verbs (analyze, evaluate, create, identify, demonstrate — not just 'understand' or 'learn about')",
        "- Objectives placed consistently in a predictable location across modules",
        "- Objectives connected to what students will do or produce",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Module objectives missing from most modules",
        "- Objectives vague or not measurable (only 'understand' or 'learn about')",
        "- Objectives appear in only one or two modules, not consistently",
        "- No connection between objectives and course-level outcomes",
        "",
        "RATING SCALE:",
        "- incomplete: Module objectives not found or present in very few modules.",
        "- approaching: Some objectives present but inconsistently placed, vague, not measurable, or not aligned to course-level outcomes.",
        "- aligned: Module learning objectives are present in the majority of modules, consistently placed, and describe specific measurable outcomes using action verbs. They connect to course-level objectives.",
        "- exceptional: Meets ALL aligned criteria AND objectives are written in student-centered language explaining what students will do, why it matters, and how it connects to future learning.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="2.2"),
    ])
}

# Element 2.3
elements["2.3"] = {
    "id": "2.3",
    "title": "Module Alignment",
    "section": "2",
    "context_scope": ["modules", "pages", "assignments"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 2.3 — Module Alignment",
        "",
        "WHAT THIS EVALUATES: Whether module content and assessments align with the module objectives and are adequate to support achievement of those objectives.",
        "",
        "WHERE TO LOOK: Module pages, assignments, discussions, and assessments within each module; compare against stated module objectives.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Learning materials that support the knowledge/skills described in objectives",
        "- Activities that allow students to practice the skills named in objectives",
        "- Assessments that measure the learning outcomes described in objectives",
        "- Clear connection between what students are asked to do and what objectives state",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Module objectives are absent (making alignment impossible to assess)",
        "- Activities and assessments do not relate to stated objectives",
        "- Content provided does not support the skills described in objectives",
        "- Assessments measure different skills than those in objectives",
        "",
        "RATING SCALE:",
        "- incomplete: No discernible connection between module content/assessments and stated objectives, or objectives are absent.",
        "- approaching: Some alignment exists but notable gaps where assessments don't match objectives or content doesn't support stated outcomes.",
        "- aligned: Module content and assessments visibly align with stated module objectives. Activities and assessments address the skills/knowledge described in the objectives.",
        "- exceptional: Meets ALL aligned criteria AND connections between objectives, content, and assessments are explicitly explained to students.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="2.3"),
    ])
}

# Element 2.4
elements["2.4"] = {
    "id": "2.4",
    "title": "Canvas Tools and Apps",
    "section": "2",
    "context_scope": ["pages", "assignments", "modules"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 2.4 — Canvas Tools and Apps",
        "",
        "WHAT THIS EVALUATES: Whether Canvas tools and institutionally approved apps are used intentionally to ensure accessibility, reduce learning labor, and streamline student access to materials and activities.",
        "",
        "WHERE TO LOOK: Modules area, course navigation, assignment settings, discussions, quizzes, and Canvas pages.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Modules used to organize course content and activities in sequence",
        "- Assignments tool used for graded work with clear instructions and due dates",
        "- Discussions tool used for interaction activities",
        "- Resources embedded within pages rather than scattered across Files",
        "- Appropriate Canvas tool chosen for each activity type",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Content scattered across Files, Pages, and external links without structure",
        "- Students asked to submit work through email instead of Assignments",
        "- Many unnecessary external links when Canvas-native tools would suffice",
        "- Activities lack clear instructions or due dates",
        "",
        "RATING SCALE:",
        "- incomplete: Canvas tools not used effectively; content disorganized with no clear module structure.",
        "- approaching: Some effective use of Canvas tools but inconsistencies (content outside modules, tools used for wrong purpose, missing instructions).",
        "- aligned: Canvas tools are used appropriately and intentionally — Modules for organization, Assignments for graded work, Discussions for interaction — streamlining access and reducing unnecessary steps for students.",
        "- exceptional: Meets ALL aligned criteria AND tools support student voices and encourage connections with classmates or the community.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="2.4"),
    ])
}

# Element 2.5
elements["2.5"] = {
    "id": "2.5",
    "title": "Use of Multimedia",
    "section": "2",
    "context_scope": ["pages", "assignments"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 2.5 — Use of Multimedia",
        "",
        "WHAT THIS EVALUATES: Whether the course consistently uses multiple types of accessible media (text, audio, video, images) to support learning, and whether content reflects diverse perspectives.",
        "",
        "WHERE TO LOOK: Module pages, readings, assignments, discussions, and instructional materials throughout the course.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Use of at least two media types beyond plain text (video, audio, images, interactive) across multiple modules",
        "- Media that supports understanding of content (not just decoration)",
        "- Accessible media practices (captioned videos, images with alt text)",
        "- Content reflecting diverse perspectives, authors, or cultural contexts",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Content presented almost entirely through text with no multimedia",
        "- Multimedia used in only one or two modules, not consistently",
        "- Media entirely inaccessible (no captions, no alt text)",
        "- No evidence of diverse perspectives in content or authors",
        "",
        "RATING SCALE:",
        "- incomplete: Course content relies almost exclusively on one format (typically text) with no meaningful multimedia.",
        "- approaching: Some multimedia present but used inconsistently (only a few modules), OR media is largely inaccessible, OR no diversity in perspectives evident.",
        "- aligned: The course consistently uses multiple media types (text plus at least video, audio, or images) across modules to support learning. Media meets basic accessibility standards. Content reflects diverse perspectives through varied authors, examples, or cultural contexts — an explicit diversity statement is NOT required if materials themselves reflect diverse voices.",
        "- exceptional: Meets ALL aligned criteria AND media is used creatively and intentionally with a wide range of low-burden formats.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="2.5"),
    ])
}

# Element 2.6
elements["2.6"] = {
    "id": "2.6",
    "title": "Guidance for Working with Content",
    "section": "2",
    "context_scope": ["pages", "assignments"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 2.6 — Guidance for Working with Content",
        "",
        "WHAT THIS EVALUATES: Whether the course provides instructions guiding students in how to engage with content, giving them direction beyond simply listing resources.",
        "",
        "WHERE TO LOOK: Module overview pages, Canvas pages containing readings or videos, assignment instructions, discussion prompts.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Instructions placed near readings, videos, or external resources telling students what to focus on",
        "- Suggestions to take notes, reflect, or attend to specific concepts",
        "- Explanations of how content connects to upcoming assignments or discussions",
        "- Introductory/framing text before resources that gives context",
        "- Weekly overviews that contextualize module content",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Resources provided as bare lists of links with zero framing or context",
        "- Content pages contain only embedded media with no surrounding guidance",
        "- Students never told how to engage with or what to focus on in materials",
        "- No connection made between content and assessments/activities",
        "",
        "RATING SCALE:",
        "- incomplete: No guidance provided for engaging with course content; resources listed without context or instructions.",
        "- approaching: Some guidance exists but the majority of content pages provide no framing, context, or direction.",
        "- aligned: The course provides instructions that guide students in engaging with content in multiple modules. This includes framing text, focus guidance, note-taking suggestions, or explanations connecting content to activities. Evidence of this guidance must appear in more than one isolated instance.",
        "- exceptional: Meets ALL aligned criteria AND instructions explicitly explain how content supports learning and anticipate common challenges.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="2.6"),
    ])
}

# Element 3.1
elements["3.1"] = {
    "id": "3.1",
    "title": "Initial Course Contact",
    "section": "3",
    "context_scope": ["pages", "announcements", "syllabus"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 3.1 — Initial Course Contact",
        "",
        "WHAT THIS EVALUATES: Whether the instructor provides a welcome message that gives students key information needed to start the course, including first-week requirements, technology overview, and support links.",
        "",
        "WHERE TO LOOK: Start Here or Orientation module, Welcome page, syllabus, and announcements.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A welcome message introducing the course and instructor",
        "- Clear instructions for what students should do first",
        "- References to first-week activities or expectations",
        "- Basic information about tools or support resources to get started",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No welcome message or initial contact found",
        "- A welcome exists but provides no actionable first steps",
        "- First-week expectations completely missing",
        "- Message is generic boilerplate with no course-specific guidance",
        "",
        "RATING SCALE:",
        "- incomplete: No welcome message or initial course contact found.",
        "- approaching: A welcome message exists but is missing key starting information (first steps, first-week expectations, or how to get help).",
        "- aligned: The instructor provides a welcome message with key information students need to start: what to do first, first-week expectations, and basic orientation to the course. The tone is welcoming and supportive.",
        "- exceptional: Meets ALL aligned criteria AND the instructor sends more than one welcome message fostering belonging.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="3.1"),
    ])
}

# Element 3.2
elements["3.2"] = {
    "id": "3.2",
    "title": "Instructor-Initiated Interaction",
    "section": "3",
    "context_scope": ["syllabus", "pages", "modules"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 3.2 — Instructor-Initiated Interaction",
        "",
        "WHAT THIS EVALUATES: Whether the course includes a clear explanation of when and how the instructor will initiate regular interaction with students.",
        "",
        "WHERE TO LOOK: Syllabus, Start Here/Orientation module, communication plan page, and course design evidence (weekly overviews, discussion facilitation notes).",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A clear explanation of instructor communication methods and frequency",
        "- Stated schedule for instructor-initiated contact (weekly announcements, videos, etc.)",
        "- Description of instructor presence in discussions or feedback",
        "- Response times or feedback timelines stated",
        "- Course structure that supports the stated plan (weekly pages exist if weekly contact promised)",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No explanation of how/when the instructor will initiate interaction",
        "- No communication plan or stated interaction schedule",
        "- Vague mention of 'staying in touch' without specifics on method, frequency, or timing",
        "- Instructor interaction implied by course structure but never explicitly described",
        "",
        "RATING SCALE:",
        "- incomplete: No explanation of how or when the instructor will initiate interaction.",
        "- approaching: Only vague mention of instructor communication with no specifics about frequency, method, or timing.",
        "- aligned: The course includes a clear, explicit explanation of when and how the instructor will initiate regular interaction (e.g., weekly announcements, discussion participation, feedback schedule). A single comprehensive communication plan covering multiple interaction types is sufficient — it need not be repeated in every module.",
        "- exceptional: Meets ALL aligned criteria AND explains why RSI matters and provides deeper interaction throughout.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="3.2"),
    ])
}

# Element 3.3
elements["3.3"] = {
    "id": "3.3",
    "title": "Student-Initiated Interaction",
    "section": "3",
    "context_scope": ["syllabus", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 3.3 — Student-Initiated Interaction",
        "",
        "WHAT THIS EVALUATES: Whether students can easily locate instructor contact information and details about regular opportunities for interaction, including expected response times.",
        "",
        "WHERE TO LOOK: Syllabus, Orientation/Getting Started module, homepage, or a communication/contact page.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Instructor name and preferred contact method clearly stated",
        "- Expected response times for messages explicitly provided",
        "- Office hours or other interaction opportunities mentioned",
        "- Contact information easy to locate",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Contact information missing entirely",
        "- No response time expectations stated anywhere",
        "- Contact method listed without response time commitment",
        "- Information present but difficult to locate",
        "",
        "RATING SCALE:",
        "- incomplete: Instructor contact information and response time expectations not found.",
        "- approaching: Some contact information present but missing response times, OR difficult to locate, OR lacks clear direction on how to reach the instructor.",
        "- aligned: Students can easily locate instructor contact information (name, preferred method) AND expected response times are clearly stated. Opportunities for interaction during the course are identified.",
        "- exceptional: Meets ALL aligned criteria AND multiple contact methods provided with encouragement to reach out at different points.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="3.3"),
    ])
}

# Element 3.4
elements["3.4"] = {
    "id": "3.4",
    "title": "Facilitation of Student Interaction",
    "section": "3",
    "context_scope": ["discussions", "assignments", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 3.4 — Facilitation of Student Interaction",
        "",
        "WHAT THIS EVALUATES: Whether the course includes opportunities for student-to-student interaction focused on course content, and whether the instructor's role in facilitating these interactions is explained.",
        "",
        "WHERE TO LOOK: Discussions, peer review assignments, group work, collaborative activities, communication plan, and any page explaining instructor facilitation.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Discussion activities requiring engagement with peers (responding to classmates, not just posting)",
        "- Peer review or peer evaluation assignments",
        "- Clear instructions guiding how students should interact with each other",
        "- An explanation of how the instructor will facilitate or participate in student interactions — this may appear in a communication plan, discussion guidelines page, or within discussion/activity instructions",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No structured opportunities for student-to-student interaction about course content",
        "- Discussions require only initial posts with no peer engagement requirement",
        "- Instructor's facilitation role never addressed anywhere (not in communication plan, discussion guidelines, or activity instructions)",
        "",
        "RATING SCALE:",
        "- incomplete: No opportunities for student-to-student interaction found, or instructor facilitation role completely unaddressed.",
        "- approaching: Interaction opportunities exist but EITHER lacking meaningful peer engagement requirements (posts only, no replies required) OR the instructor's facilitation role is never addressed.",
        "- aligned: The course includes structured opportunities for student-to-student interaction focused on content (discussions requiring replies, peer review/evaluation, collaboration) AND the instructor's role in facilitating these interactions is explained. The facilitation explanation may appear in a communication plan, discussion guidelines, or activity instructions. IMPORTANT: Statements such as 'I will monitor discussions daily and chime in with opinions and clarifications', 'I participate in discussions', 'I provide feedback on peer evaluations', or 'I will be reading and responding to your posts' all constitute an explanation of the instructor's facilitation role and satisfy this requirement. The explanation does NOT need to use the word 'facilitate' — any description of instructor presence in or oversight of student interactions counts.",
        "- exceptional: Meets ALL aligned criteria AND the instructor demonstrates active facilitation with structured activities and clear inclusivity guidelines.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="3.4"),
    ])
}

# Element 4.1
elements["4.1"] = {
    "id": "4.1",
    "title": "Variety & Frequency",
    "section": "4",
    "context_scope": ["assignments", "quizzes", "discussions"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 4.1 — Variety & Frequency",
        "",
        "WHAT THIS EVALUATES: Whether the course provides relevant formative and summative assessments throughout the term, offering different ways for students to demonstrate learning.",
        "",
        "WHERE TO LOOK: Discussions, assignments, quizzes, projects, and other graded activities across modules.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A combination of formative assessments (practice quizzes, reflections, drafts, low-stakes discussions) AND summative assessments (essays, projects, exams)",
        "- Multiple assessment types (not just one format repeated)",
        "- Assessments distributed across modules/units throughout the term",
        "- At least three distinct assessment formats present",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Course relies primarily on one type of assessment (only quizzes, or only discussions)",
        "- Assessments concentrated at beginning or end, not distributed throughout",
        "- No formative assessment opportunities (everything is high-stakes)",
        "- Only two assessment formats used across the entire course",
        "",
        "RATING SCALE:",
        "- incomplete: Very limited assessment types or assessments not distributed throughout the term.",
        "- approaching: Some variety exists but limited to two formats, or assessments not regularly distributed throughout the course.",
        "- aligned: The course provides both formative and summative assessments distributed throughout the term with at least three distinct assessment formats (e.g., discussions, quizzes, essays, projects, reflections).",
        "- exceptional: Meets ALL aligned criteria AND most assessments support higher-order thinking and connect to real-world situations.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="4.1"),
    ])
}

# Element 4.2
elements["4.2"] = {
    "id": "4.2",
    "title": "Scoring Criteria",
    "section": "4",
    "context_scope": ["assignments", "discussions"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 4.2 — Scoring Criteria",
        "",
        "WHAT THIS EVALUATES: Whether assessments include a clear explanation of how student work will be evaluated, such as rubrics or defined expectations.",
        "",
        "WHERE TO LOOK: Assignment instructions, discussion prompts, quizzes, and any references to rubrics or grading criteria within activities.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- References to rubrics being used for grading (e.g., 'see rubric', 'graded using the attached rubric', 'view rubric for criteria')",
        "- Clearly described grading criteria within assignment instructions",
        "- Point values, word counts, or performance expectations stated",
        "- Evaluation criteria described for major assessments",
        "- Evidence that a consistent grading approach is communicated to students",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No grading criteria, rubric references, or evaluation expectations found in any assessments",
        "- Students cannot determine how their work will be evaluated from any available information",
        "- Only point values listed with no explanation of what earns those points",
        "",
        "RATING SCALE:",
        "- incomplete: No scoring criteria, rubrics, or defined expectations found for assessments.",
        "- approaching: Some scoring criteria present but only on a few assessments, or criteria are too vague to guide student work.",
        "- aligned: Assessments include evidence that scoring criteria are provided — either through rubric references in assignment instructions, stated evaluation criteria, or clear performance expectations. A consistent pattern of referencing rubrics or stating expectations across multiple assessments demonstrates alignment. Note: In LMS exports, rubrics are often attached separately and may not appear in exported text; references to rubrics ('see rubric', 'rubric attached', 'graded using rubric') count as evidence.",
        "- exceptional: Meets ALL aligned criteria AND includes examples or models of student work to clarify expectations.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="4.2"),
    ])
}

# Element 4.3
elements["4.3"] = {
    "id": "4.3",
    "title": "Assessment Instructions",
    "section": "4",
    "context_scope": ["assignments", "quizzes", "discussions"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 4.3 — Assessment Instructions",
        "",
        "WHAT THIS EVALUATES: Whether accessible instructions clearly explain what students need to do to complete assignments successfully and provide relevant resources.",
        "",
        "WHERE TO LOOK: Assignments, discussions, quizzes, and other graded activities in course modules.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Instructions describing the purpose or context of the assignment",
        "- Clear directions for completing the task (what to do, how to do it)",
        "- Submission requirements stated (format, length, where to submit)",
        "- Due dates clearly communicated",
        "- Links to relevant resources supporting task completion",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- Instructions unclear or so brief students cannot determine what to do",
        "- Submission details (how, where, format) missing",
        "- Due dates not communicated",
        "- Most assessments lack clear step-by-step guidance",
        "",
        "RATING SCALE:",
        "- incomplete: Assessment instructions missing or so incomplete that students cannot determine what to do.",
        "- approaching: Instructions present but missing key elements (purpose, submission details, due dates, or resources) on the majority of assessments.",
        "- aligned: The majority of assessments have clear instructions explaining what students need to do, how to submit, and when it is due. Relevant resources or links are provided where appropriate.",
        "- exceptional: Meets ALL aligned criteria AND instructions offered in multiple formats to support different learning needs.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="4.3"),
    ])
}

# Element 4.4
elements["4.4"] = {
    "id": "4.4",
    "title": "Assessment Feedback",
    "section": "4",
    "context_scope": ["assignments", "syllabus", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 4.4 — Assessment Feedback",
        "",
        "WHAT THIS EVALUATES: Whether the course clearly explains how and when students will receive feedback on their work.",
        "",
        "WHERE TO LOOK: Syllabus, Start Here/Orientation module, a dedicated feedback/grading page, and within assessment instructions.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A statement describing expected feedback timelines (e.g., 'within 3-5 days')",
        "- Information about how feedback will be delivered (comments, rubrics, annotations)",
        "- Students told where to find feedback in the LMS",
        "- Feedback process explained clearly in at least one accessible location",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No explanation anywhere of when or how feedback will be provided",
        "- No stated timeline for receiving feedback",
        "- Students have no way to know when or where to expect feedback",
        "- Feedback mentioned only in passing with no specifics",
        "",
        "RATING SCALE:",
        "- incomplete: No explanation of how or when students will receive feedback found in the course.",
        "- approaching: Feedback is vaguely mentioned but no specific timeline, format, or location details provided.",
        "- aligned: The course clearly explains how and when students will receive feedback — including a timeline and method/location. This may appear in a centralized location (grading page, communication plan, syllabus) and does NOT need to be in every assessment.",
        "- exceptional: Meets ALL aligned criteria AND provides clear instructions for accessing feedback in the LMS with opportunities to use feedback to improve.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="4.4"),
    ])
}

# Element 4.5
elements["4.5"] = {
    "id": "4.5",
    "title": "Learner Self-Reflection",
    "section": "4",
    "context_scope": ["assignments", "discussions", "pages"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 4.5 — Learner Self-Reflection",
        "",
        "WHAT THIS EVALUATES: Whether the course provides multiple opportunities for students to reflect on their learning and receive formative feedback.",
        "",
        "WHERE TO LOOK: Assignments, discussions, journals, quizzes, or reflection prompts within modules.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- Reflection prompts or assignments asking students to think about their learning process",
        "- Learning journals, progress reflections, or self-assessment activities",
        "- Multiple reflection opportunities distributed throughout the course (not just one)",
        "- Reflections connected to learning goals or personal growth",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No self-reflection opportunities found in the course",
        "- Only one reflection activity in the entire course (not 'multiple')",
        "- Reflection prompts that are actually content questions, not metacognitive reflection",
        "- Reflections present but no connection to formative feedback",
        "",
        "RATING SCALE:",
        "- incomplete: No self-reflection opportunities found in the course.",
        "- approaching: Only one reflection activity present, or reflection prompts are unclear/disconnected from learning goals.",
        "- aligned: The course provides multiple opportunities (more than one, distributed across the term) for students to reflect on their learning. Reflections invite metacognitive thinking about the learning process, not just content recall.",
        "- exceptional: Meets ALL aligned criteria AND reflection opportunities help students connect effort to results and plan for improvement.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="4.5"),
    ])
}

# Element 4.6
elements["4.6"] = {
    "id": "4.6",
    "title": "Learner Feedback Survey",
    "section": "4",
    "context_scope": ["pages", "assignments", "syllabus"],
    "requires": [],
    "evaluation_prompt": "\n".join([
        "ELEMENT 4.6 — Learner Feedback Survey",
        "",
        "WHAT THIS EVALUATES: Whether the course provides an anonymous or confidential opportunity for learners to give feedback to the instructor regarding course design and/or content.",
        "",
        "WHERE TO LOOK: Modules in the second half of the course, final module or closing activity; may also be referenced in the syllabus or as an ungraded assignment/survey.",
        "",
        "WHAT DEMONSTRATES ALIGNMENT:",
        "- A survey or feedback form placed in the second half or near the end of the course",
        "- Anonymous or confidential feedback mechanism about course design, pacing, or content",
        "- Clear invitation for students to share their experience",
        "- Survey described as ungraded, anonymous, confidential, or 'for the instructor only'",
        "- Questions about course pacing, workload, clarity of instructions, or what to keep/change",
        "",
        "COMMON ISSUES THAT PREVENT ALIGNMENT:",
        "- No feedback survey or opportunity found anywhere in the course",
        "- Only a generic reference to institutional evaluations without a course-specific mechanism",
        "- Feedback mechanism requires students to identify themselves with no privacy assurance",
        "- No explicit invitation for students to provide course feedback",
        "",
        "RATING SCALE:",
        "- incomplete: No course feedback survey or mechanism found in the course content.",
        "- approaching: A feedback mechanism exists but lacks privacy assurance (not anonymous/confidential), or is not clearly about course design/content feedback.",
        "- aligned: The course provides an opportunity (in the second half or near the end) for learners to give anonymous or confidential feedback to the instructor about course design and/or content. An ungraded survey with privacy assurance ('your responses are for me', 'does not affect your grade', 'anonymous', 'confidential') that asks about course experience qualifies. Multiple feedback check-ins distributed through the course also satisfy this requirement.",
        "- exceptional: Meets ALL aligned criteria AND provides feedback opportunities at multiple points throughout the course.",
        "- not_evaluable: Use ONLY when the supplied Course Content is empty, contains the literal no-content marker, or is wholly unrelated/unusable.",
        "",
        DECISION_RULES_TEMPLATE,
        "",
        RESPONSE_DISCIPLINE,
        "",
        OUTPUT_TEMPLATE.format(eid="4.6"),
    ])
}

# Write the final JSON
output = {
    "version": "2027.06",
    "prompt_version": "2027.06.5",
    "elements": elements
}

import os
out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "cvc_rubric", "rubric_prompts.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print(f"Written {len(elements)} elements to {out_path}")
print(f"Prompt version: {output['prompt_version']}")
